### ISSUE TITLE
uh - zero size

### ISSUE THREAD

**Issue by vance** [angular-ui/ui-slider#91] opened 2015-10-07 20:19 UTC
I get the directive to load, I used the included css... but sliders and tracks have zero height. i force them to have background colors and height for testing, but the rendered output  is always 0px 0px despite inspection the CSS that says otherwise. I can even click in the track and move the mouse around I see the left:x% change, but can't see anything.

**Comment by PowerKiKi** [comment] 2015-10-12 02:52
Pease create a minimal reproductible case on plunkr. Since the demo is working, there must be something different (wrong?) with the way it is used in your case

**Comment by ElDudelino** [comment] 2017-04-05 09:37
Had the same issue today. The cause was that JQuery was included after Angular resulting in the known "elm.slider is not a function" issue.

**Comment by PowerKiKi** [comment] 2017-04-05 10:45
Thanks for your feedback, closing this, since it's not really an issue with ui-slider.

**Closed by PowerKiKi** 2017-04-05 10:45 UTC
Labels: need feedback
